spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.42.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

# 项目的所有url的前缀 使所有controller路径前都加上一个sell
server:
  servlet:
    context-path: /sell